# Generated by Django 3.1.3 on 2021-04-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_subject', models.CharField(max_length=25)),
                ('story_content', models.TextField()),
                ('story_datetime', models.DateTimeField()),
                ('story_password', models.CharField(max_length=4)),
            ],
        ),
    ]
