# Generated by Django 3.1.3 on 2021-04-28 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Story',
            new_name='Scene',
        ),
        migrations.RenameField(
            model_name='scene',
            old_name='story_content',
            new_name='scene_content',
        ),
        migrations.RenameField(
            model_name='scene',
            old_name='story_datetime',
            new_name='scene_datetime',
        ),
        migrations.RenameField(
            model_name='scene',
            old_name='story_password',
            new_name='scene_password',
        ),
        migrations.RenameField(
            model_name='scene',
            old_name='story_subject',
            new_name='scene_subject',
        ),
    ]
