# Generated by Django 3.1.3 on 2021-04-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0002_auto_20210428_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='scene_subject',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
